name: Build & Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build_and_release:
    name: Build packages and release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            CMD_BUILD: >
                pyinstaller -F -w -n torf-gui torfGUI/gui.py &&
                cd dist/ &&
                zip -r9 torf-gui-macOS torf-gui.app/
            OUT_FILE_NAME: torf-gui-macOS.zip
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: pyinstaller -F -w -n torf-gui-win64 torfGUI/gui.py
            OUT_FILE_NAME: torf-gui-win64.exe
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build with pyinstaller for ${{matrix.TARGET}}
      run: ${{matrix.CMD_BUILD}}
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        generate_release_notes: true
        prerelease: false
        files: |
          dist/${{matrix.OUT_FILE_NAME}}


permissions:
  contents: write