name: Build & Release

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build_and_release:
    name: Build packages and release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest-large
            TARGET: macos-x86_64
            CMD_BUILD: >
              pyinstaller -F -w -n torf-gui --target-arch x86_64 torf_gui/gui.py &&
              cd dist/ &&
              zip -r9 torf-gui-macOS-x86_64 torf-gui.app/
            OUT_FILE_NAME: torf-gui-macOS-x86_64.zip
          - os: macos-latest
            TARGET: macos-arm64
            CMD_BUILD: >
              pyinstaller -F -w -n torf-gui --target-arch arm64 torf_gui/gui.py &&
              cd dist/ &&
              zip -r9 torf-gui-macOS-arm64 torf-gui.app/
            OUT_FILE_NAME: torf-gui-macOS-arm64.zip
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: pyinstaller -F -w -n torf-gui-win64 torf_gui/gui.py
            OUT_FILE_NAME: torf-gui-win64.exe
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: ">=3.7 <3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Build with pyinstaller for ${{matrix.TARGET}}
        run: ${{matrix.CMD_BUILD}}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          prerelease: false
          files: |
            dist/${{matrix.OUT_FILE_NAME}}

permissions:
  contents: write
